branches:
  only:
  - master

language: node_js

sudo: false

node_js:
  - '0.12'

before_install:
  - openssl aes-256-cbc -K $encrypted_2e8cc0dc8a9b_key -iv $encrypted_2e8cc0dc8a9b_iv -in ssh_key_travis.enc -out ssh_key_travis -d
  - cp ssh_key_travis ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .ssh_config ~/.ssh/config
  - git config --global user.name "Clarence-pan"
  - git config --global user.email "clarence-pan@foxmail.com"
  - git clone -b master git@github.com:Clarence-pan/clarence-pan.github.io.git .deploy_git

install:
  - npm install hexo-cli -g
  - npm install
  - npm install hexo-generator-feed --save
  - npm install hexo-generator-sitemap --save
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-tag --save
  - npm install hexo-generator-category --save
  - npm install hexo-renderer-less --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-generator-index --save
  - cat package.json

script:
  - hexo clean
  - hexo generate
  - hexo deploy
